### ISSUE TITLE
when will this be a pip supported package? 

### ISSUE THREAD

**Issue by shyamcody** [koaning/forcy#1]
Hey @koaning this looks like a nice visualization package. I have been trying out different spacy visualization techniques and would like to try out forcy too. But I can't download it via pip. What is the ETA for pip support for this package?

**Comment by koaning** [comment]
I mean ... I started hacking on this last night. I wouldn't say it's anywhere near done yet. Once done I might consider pip, but we're not there just yet.

**Comment by koaning** [comment]
Also ... I'm not 100% sure if this really needs to be a package. You could pip install via github too.
